<?php
return array (
  'posname' => 
  array (
    'fieldid' => '137',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'posname',
    'name' => '类型',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u4e2a\\u4eba\\u5fae\\u535a|0\\r\\n\\u516c\\u5171\\u5fae\\u535a|1","boxtype":"radio","fieldtype":"int","minnumber":"1","cols":"5","width":"80","size":"1","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '个人微博|0
公共微博|1',
    'boxtype' => 'radio',
    'fieldtype' => 'int',
    'minnumber' => '1',
    'cols' => '5',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
  ),
  'con' => 
  array (
    'fieldid' => '136',
    'modelid' => '13',
    'siteid' => '1',
    'field' => 'con',
    'name' => '留言内容',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => '{"width":"100","height":"320","defaultvalue":"","enablehtml":"0"}',
    'formattribute' => 'placeholder="请留下你的脚步"',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '100',
    'height' => '320',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
);
?>