<?php
return array (
  0 => 
  array (
    'id' => '86',
    'catid' => '26',
    'typeid' => '0',
    'title' => '翼城中学招聘启事',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 启事 中学',
    'description' => '翼城中学招聘启事   翼城中学招聘保安3人（55岁以下，男性，高中毕业，复转军人优先），门卫5人（65岁以下，男性，教育部门退休人员优先   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=26&id=86',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489152395',
    'updatetime' => '1489152525',
  ),
  1 => 
  array (
    'id' => '85',
    'catid' => '26',
    'typeid' => '0',
    'title' => '翼城中学澡堂招标',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 澡堂 中学',
    'description' => '翼城中学澡堂招标公告   翼城中学澡堂实行学校统一管理、个体经营的运营方式，现公开招标。报名条件：    具有本县户籍，政治素质高   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=26&id=85',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489152347',
    'updatetime' => '1489152393',
  ),
  2 => 
  array (
    'id' => '84',
    'catid' => '26',
    'typeid' => '0',
    'title' => '翼城中学超市招标',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 超市 中学',
    'description' => '翼城中学超市招标公告   翼城中学超市实行学校统一管理、个体经营的运营方式，现公开招标。  报名条件：   具有本县户籍，政治素质   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=26&id=84',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489152168',
    'updatetime' => '1489152345',
  ),
  3 => 
  array (
    'id' => '83',
    'catid' => '26',
    'typeid' => '0',
    'title' => '翼城中学食堂经营招标',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 食堂 中学',
    'description' => '翼城中学食堂经营招标公告   翼城中学食堂实行学校统一管理，委托实体独立经营的运营方式，现公开招标。具备下列条件之一者均可报名。    ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=26&id=83',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489151855',
    'updatetime' => '1489152164',
  ),
  4 => 
  array (
    'id' => '77',
    'catid' => '26',
    'typeid' => '0',
    'title' => '2015 级高一军训',
    'style' => '',
    'thumb' => 'http://www.sxyczx.com.cn/admin/edit/UploadFile/20151019105048998.jpg',
    'keywords' => '高一',
    'description' => '',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=26&id=77',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487245701',
    'updatetime' => '1487245786',
  ),
);
?>