<?php
return array (
  0 => 
  array (
    'id' => '69',
    'catid' => '43',
    'typeid' => '0',
    'title' => '翼城中学关于开展第六届英语周活动的通知',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 英语 第六届',
    'description' => '高二年级各团支部：   为推进校园文化建设，提高学生英语口语表达能力，激发学生英语学习的兴趣，形成英语会话的良好氛围，校团委决定在   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=43&id=69',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487231523',
    'updatetime' => '1487231615',
  ),
  1 => 
  array (
    'id' => '68',
    'catid' => '43',
    'typeid' => '0',
    'title' => '翼城中学招聘启事',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 启事 中学',
    'description' => '翼城中学招聘启事   翼城中学招聘保安3人（55岁以下，男性，高中毕业，复转军人优先），门卫5人（65岁以下，男性，教育部门退休人员优先   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=43&id=68',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487231427',
    'updatetime' => '1489152532',
  ),
  2 => 
  array (
    'id' => '67',
    'catid' => '43',
    'typeid' => '0',
    'title' => '翼城中学澡堂招标',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 澡堂 中学',
    'description' => '翼城中学澡堂招标公告   翼城中学澡堂实行学校统一管理、个体经营的运营方式，现公开招标。报名条件：    具有本县户籍，政治素质高   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=43&id=67',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487231258',
    'updatetime' => '1489152397',
  ),
  3 => 
  array (
    'id' => '66',
    'catid' => '43',
    'typeid' => '0',
    'title' => '翼城中学超市招标',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 超市 中学',
    'description' => '翼城中学超市招标公告   翼城中学超市实行学校统一管理、个体经营的运营方式，现公开招标。  报名条件：   具有本县户籍，政治素质   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=43&id=66',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487231107',
    'updatetime' => '1487231256',
  ),
  4 => 
  array (
    'id' => '65',
    'catid' => '43',
    'typeid' => '0',
    'title' => '翼城中学食堂经营招标',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 食堂 中学',
    'description' => '翼城中学食堂经营招标公告   翼城中学食堂实行学校统一管理，委托实体独立经营的运营方式，现公开招标。具备下列条件之一者均可报名。    ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=43&id=65',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487230984',
    'updatetime' => '1489152181',
  ),
);
?>