<?php
return array (
  0 => 
  array (
    'id' => '91',
    'catid' => '12',
    'typeid' => '0',
    'title' => '你知道奔跑和漫步的不同吗？',
    'style' => '',
    'thumb' => '',
    'keywords' => '你知道奔跑和漫步的不同吗？',
    'description' => '353尉桢桢   不就是一个跑，一个走。   不你错了，所有的奔跑都会有一个腾空的过程。   就像青春过程中的那些失败，痛苦都会过去   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=12&id=91',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489154581',
    'updatetime' => '1489154805',
  ),
  1 => 
  array (
    'id' => '90',
    'catid' => '12',
    'typeid' => '0',
    'title' => '舞动青春，赢在拼搏',
    'style' => '',
    'thumb' => '',
    'keywords' => '青春',
    'description' => '358班   韩林：我们撇下了无知，迎来了属于我们的青春。   曹纯玉：青春让我们肆无忌惮，畅然释怀，体味风那样的自在，感受那云般的   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=12&id=90',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489154436',
    'updatetime' => '1489154579',
  ),
  2 => 
  array (
    'id' => '89',
    'catid' => '12',
    'typeid' => '0',
    'title' => '不要忽略沿途风景',
    'style' => '',
    'thumb' => '',
    'keywords' => '风景',
    'description' => '333班 张瑶   我们总是欣赏蓝天的广阔而忽略了点缀蓝天的白云；   我们总是陶醉于花朵的艳丽而忽略了装扮红花的绿叶；我们总是心中   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=12&id=89',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489154318',
    'updatetime' => '1489154410',
  ),
  3 => 
  array (
    'id' => '88',
    'catid' => '12',
    'typeid' => '0',
    'title' => '不要错过身边的风景',
    'style' => '',
    'thumb' => '',
    'keywords' => '错过 风景',
    'description' => '334班 王武荣  志愿者们由于专家的引导，只注意了蓝色，却忽视了更漂亮的其他色彩的物品。我们又何尝不是，总是由于客观因素，而忽视更   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=12&id=88',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489154085',
    'updatetime' => '1489154240',
  ),
  4 => 
  array (
    'id' => '82',
    'catid' => '12',
    'typeid' => '0',
    'title' => '积极开展感恩教育活动 促进未成年人身心健康成长',
    'style' => '',
    'thumb' => '',
    'keywords' => '身心健康 未成年人',
    'description' => ' 翼城中学是山西省示范高中之一，省级德育示范校。多年来，学校在以学生发展为本，为学生成长奠基的办学理念引领下，牢固确立德育无痕，德   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=12&id=82',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1488506706',
    'updatetime' => '1488586277',
  ),
);
?>