<?php
return array (
  0 => 
  array (
    'id' => '93',
    'catid' => '16',
    'typeid' => '0',
    'title' => '翼城中学“四步备课”要求',
    'style' => '',
    'thumb' => '',
    'keywords' => '翼城 中学',
    'description' => '认真搞好四步备课，是实施我校目标引领、四步导学课堂教学模式的重要保证。为此，需要集中全组每个教师的智慧备好课，由备课组长牵头，把四   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=16&id=93',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489156804',
    'updatetime' => '1489156927',
  ),
  1 => 
  array (
    'id' => '92',
    'catid' => '16',
    'typeid' => '0',
    'title' => '我校学生制作的部分生物模型',
    'style' => '',
    'thumb' => 'http://localhost/yczx/install_package/uploadfile/2017/0310/20170310102945606.jpg',
    'keywords' => '模型 生物 部分',
    'description' => '',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=16&id=92',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489156049',
    'updatetime' => '1489156223',
  ),
  2 => 
  array (
    'id' => '55',
    'catid' => '16',
    'typeid' => '0',
    'title' => '试题集锦：南昌二中高三化学模拟卷',
    'style' => '',
    'thumb' => '',
    'keywords' => '二中 试题集锦 南昌',
    'description' => 'http:  localhost yczx install_package uploadfile 2017 0214 20170214012004274 txt',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=16&id=55',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487049022',
    'updatetime' => '1487052142',
  ),
  3 => 
  array (
    'id' => '54',
    'catid' => '16',
    'typeid' => '0',
    'title' => '网络环境下课堂教学的实践与思考',
    'style' => '',
    'thumb' => '',
    'keywords' => '课堂教学 环境 网络',
    'description' => '(山东省寿光市北洛一中 武耀奎　肖在隆)　　　摘要：人类社会已进入信息时代,信息技术飞速发展，不仅渗透了各行各业及百姓家庭，也已经向   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=16&id=54',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487048957',
    'updatetime' => '1487049019',
  ),
  4 => 
  array (
    'id' => '53',
    'catid' => '16',
    'typeid' => '0',
    'title' => '中学信息技术教学模式初探',
    'style' => '',
    'thumb' => '',
    'keywords' => '教学模式 中学 技术',
    'description' => '(邓州市城区五初中微机室　贾振杰 )　　　　人类以信息技术为核心内容的现代科技竞争日趋激烈，世界各国均不同程度地加强了对中小学信息技   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=16&id=53',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1487048911',
    'updatetime' => '1487048955',
  ),
);
?>