<?php
return array (
  0 => 
  array (
    'id' => '87',
    'catid' => '27',
    'typeid' => '0',
    'title' => '聚焦十八届三中全会教育改革内容',
    'style' => '',
    'thumb' => '',
    'keywords' => '三中全会 教育改革 内容',
    'description' => '    十八届三中全会于2013年11月12日下午闭幕。为期4天的全会听取讨论了习近平受中央政治局委托作的工作报告，审议通过了《中共中央关   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=27&id=87',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1489152847',
    'updatetime' => '1489152912',
  ),
  1 => 
  array (
    'id' => '81',
    'catid' => '27',
    'typeid' => '0',
    'title' => '人大代表周洪宇描绘农村中职免费“路线图”',
    'style' => '',
    'thumb' => '',
    'keywords' => '路线图 人大代表 农村',
    'description' => '   我国实施九年免费义务教育之后，下一步免费的突破口在哪里？今年两会上，全国人大代表、华中师范大学教授周洪宇回答：应当从农村中等   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=27&id=81',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1488506324',
    'updatetime' => '1488506470',
  ),
  2 => 
  array (
    'id' => '80',
    'catid' => '27',
    'typeid' => '0',
    'title' => '温家宝：坚持优先发展教育　重点抓好五方面',
    'style' => '',
    'thumb' => 'W020090305419588521220.jpg',
    'keywords' => '温家宝 重点',
    'description' => '　3月5日，第十一届全国人民代表大会第二次会议在北京人民大会堂开幕。国务院总理温家宝作政府工作报告。 新华社记者 樊如钧摄　　3月5日   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=27&id=80',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1488506272',
    'updatetime' => '1488506322',
  ),
  3 => 
  array (
    'id' => '79',
    'catid' => '27',
    'typeid' => '0',
    'title' => '山西省中小学体育课开足率将受督查',
    'style' => '',
    'thumb' => '',
    'keywords' => '山西省 体育课 中小学',
    'description' => '   省教育厅消息，山西省将于11月18日开始对全省的中小学体育工作进行督查。体育课开足率等成为督查重点。　　据悉，此次督查的内容包括   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=27&id=79',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1488506217',
    'updatetime' => '1488506270',
  ),
  4 => 
  array (
    'id' => '78',
    'catid' => '27',
    'typeid' => '0',
    'title' => '北师大校长钟秉林:中国高考要改 但不可能取消',
    'style' => '',
    'thumb' => '',
    'keywords' => '钟秉林 北师大 中国',
    'description' => ' 浙江省的高考改革制度即将出炉。昨天，北京师范大学校长钟秉林受杭州师范大学之邀，来到浙江人文大讲堂，他表示：高考要改，但中国不可能   ',
    'posids' => '0',
    'url' => 'http://localhost/yczx/install_package/index.php?m=content&c=index&a=show&catid=27&id=78',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1488506091',
    'updatetime' => '1488506214',
  ),
);
?>